name: Kernel Builder
on: push
jobs:
  Buiding-Kernel:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Setup Environment
      run: |
        sudo apt update
        sudo apt install git make bison flex

    - name: Clone Kernel Source
      run: |
        git clone https://github.com/VThang51/android_kernel_samsung_a13xx.git -b A135FXXU5DXA4_SWA kernel

    - name: Clone Toolchain
      run: |
        cd kernel
        git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 -b android12L-release toolchain/clang/host/linux-x86
        git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android12L-release toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9

    - name: Building Kernel
      run: |
        cd kernel
        export PLATFORM_VERSION=12
        export ANDROID_MAJOR_VERSION=s
        export ARCH=arm64 
        make exynos850-a13xx_defconfig
        make

    - uses: actions/upload-artifact@v4
      with:
        name: prebuilt
        path: |
          kernel/arch/arm64/boot/*
          kernel/drivers/*/*.ko
