name: Kernel Builder (Local)
on:
  workflow_dispatch:
    inputs:
      KERNEL_URL:
        description: 'Kernel Source URL'
        required: true
        default: 'https://github.com/VThang51/android_kernel_samsung_a13xx.git'
      KERNEL_BRANCH:
        description: 'Kernel Source Branch'
        required: true
        default: 'A135FXXU5DXA4_SWA'
      TC_BRANCH:
        description: 'Toolchain Branch'
        required: true
        default: 'android12L-release'
      DEFCONFIG:
        description: '"defconfig" file'
        required: true
        default: 'exynos850-a13xx_defconfig'
jobs:
  Buiding-Kernel:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Setup Environment
      run: |
        sudo apt update
        sudo apt install git make bison flex

    - name: Clone Kernel Source
      run: |
        git clone ${{ inputs.KERNEL_URL }} -b ${{ inputs.KERNEL_BRANCH }} kernel

    - name: Clone Toolchain
      run: |
        cd kernel
        git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 -b ${{ inputs.TC_BRANCH }} toolchain/clang/host/linux-x86
        git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b ${{ inputs.TC_BRANCH }} toolchain/gcc/linux-x86/aarch64/aarch64-linux-android-4.9

    - name: Building Kernel
      run: |
        cd kernel
        export PLATFORM_VERSION=12
        export ANDROID_MAJOR_VERSION=s
        export ARCH=arm64 
        make ${{ inputs.DEFCONFIG }}
        make

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.KERNEL_BRANCH }}
        path: |
          kernel/arch/arm64/boot/*
          kernel/drivers/*/*.ko
